#!/usr/bin/env bash
# This script handles signals

FILE="/var/run/myscript.pid"
touch $FILE
PID=$(pidof $FILE)

handle_TERM()
{
	echo "I hate the kill command"
	remove_and_exit
}

handle_QUIT()
{
	remove_and_exit
}

remove_and_exit()
{
	rm -f $FILE
	kill "$PID"
}

trap handle_TERM SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap remove_and_exit SIGQUIT

while :
do
	echo "To infinity and beyond"
done
