#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this data from an apache access log file.

FILE="apache-access.log"

if [ ! -f "$FILE" ];
then
	echo "Error! File does not exist!"
fi

awk '{count[$1" "$9]++} 
     END {
         for (key in count) {
             print count[key], key
         }
     }' $FILE | sort -rn
