#!/usr/bin/env bash
# This script prints "Best School" 10 times
# but the 9th iteration prints "Hi" after

i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 9 ];
	then
		echo "Hi"
	fi
	echo "Best School"
	i=$((i+1))
done
